# -*- coding: utf-8 -*-
"""generate_invoices.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhJ0-8LbpWzrBw1EEsCKG18Zyzuq743t
"""

!pip install pandas fpdf

import pandas as pd
from fpdf import FPDF

# Load the CSV file
csv_file_path = '/content/All Bills.csv'
data = pd.read_csv(csv_file_path)

# Strip leading spaces from column names
data.columns = data.columns.str.strip()

# Inspect updated column names
print(data.columns)

# Group data by the exact column name
grouped = data.groupby('INVOICE No.')

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Invoice', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def invoice_body(self, invoice_no, date, name, address, contact, GSTIN, items):
        self.set_font('Arial', '', 12)
        self.cell(0, 10, f'Invoice No: {invoice_no}', 0, 1)
        self.cell(0, 10, f'Date: {date}', 0, 1)
        self.cell(0, 10, f'Name: {name}', 0, 1)
        self.cell(0, 10, f'Address: {address}', 0, 1)
        self.cell(0, 10, f'Contact: {contact}', 0, 1)
        self.cell(0, 10, f'GSTIN: {GSTIN}', 0, 1)
        self.ln(10)

        self.set_font('Arial', 'B', 12)
        self.cell(40, 10, 'Description', 1)
        self.cell(20, 10, 'Qty', 1)
        self.cell(30, 10, 'Price', 1)
        self.cell(30, 10, 'CGST(18%)', 1)
        self.cell(30, 10, 'SGST(18%)', 1)
        self.cell(30, 10, 'IGST(18%)', 1)
        self.cell(30, 10, 'Total Amount', 1)
        self.ln(10)

        self.set_font('Arial', '', 12)
        for index, row in items.iterrows():
            self.cell(40, 10, row['DESCRIPTION'], 1)
            self.cell(20, 10, str(row['QTY']), 1)
            self.cell(30, 10, f"${row['PRICE']:.2f}", 1)
            self.cell(30, 10, f"${row['CGST(18%)']:.2f}", 1)
            self.cell(30, 10, f"${row['SGST18%']:.2f}", 1)
            self.cell(30, 10, f"${row['IGST18%']:.2f}", 1)
            self.cell(30, 10, f"${row['TOTAL AMOUNT']:.2f}", 1)
            self.ln(10)

# Convert columns to numeric types
data['PRICE'] = pd.to_numeric(data['PRICE'], errors='coerce')
data['CGST(18%)'] = pd.to_numeric(data['CGST(18%)'], errors='coerce')
data['SGST18%'] = pd.to_numeric(data['SGST18%'], errors='coerce')
data['IGST18%'] = pd.to_numeric(data['IGST18%'], errors='coerce')
data['TOTAL AMOUNT'] = pd.to_numeric(data['TOTAL AMOUNT'], errors='coerce')

# Create PDFs for each invoice
for invoice_no, group in grouped:
    date = group['DATE'].iloc[0]
    name = group['NAME'].iloc[0]
    address = group['ADDRESS'].iloc[0]
    contact = group['CONTACT'].iloc[0]
    GSTIN = group['GSTIN'].iloc[0]
    items = group[['DESCRIPTION', 'QTY', 'PRICE', 'CGST(18%)', 'SGST18%', 'IGST18%', 'TOTAL AMOUNT']]

    pdf = PDF()
    pdf.add_page()
    pdf.invoice_body(invoice_no, date, name, address, contact, GSTIN, items)
    pdf_file_path = f'/content/Invoice_{invoice_no}.pdf'
    pdf.output(pdf_file_path)



